IF NOT EXISTS (SELECT * FROM sys.tables WHERE Name = 'Group')
BEGIN

CREATE TABLE dbo.[Group]
(
	ID INT IDENTITY(1, 1) NOT NULL,
	Number INT NOT NULL,
	Name VARCHAR(10),
	IUPAC VARCHAR(10),
	CAS VARCHAR(5),
	Family VARCHAR(20),
	DateCreatedUtc DATETIME NOT NULL,
	DateUpdatedUtc DATETIME NOT NULL,
	CONSTRAINT [PK_Group] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE dbo.[Group] ADD  CONSTRAINT [DF_Group_DateCreatedUtc]  DEFAULT (getdate()) FOR [DateCreatedUtc]
ALTER TABLE dbo.[Group] ADD  CONSTRAINT [DF_Group_DateUpdatedUtc]  DEFAULT (getdate()) FOR [DateUpdatedUtc]

END