BEGIN TRAN

INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 1), 1, 'H', 'Hydrogen', 1, 1.008, 0.00008988);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 18), 2, 'He', 'Helium', 1, 4.002602, 0.0001785);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 1), 3, 'Li', 'Lithium', 2, 6.94, 0.534);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 2), 4, 'Be', 'Beryllium', 2, 9.0121831, 1.85);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 13), 5, 'B', 'Boron', 2, 10.81, 2.34);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 14), 6, 'C', 'Carbon', 2, 12.011, 2.267);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 15), 7, 'N', 'Nitrogen', 2, 14.007, 0.0012506);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 16), 8, 'O', 'Oxygen', 2, 15.999, 0.001429);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 17), 9, 'F', 'Fluorine', 2, 18.998403163, 0.001696);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 18), 10, 'Ne', 'Neon', 2, 20.1797, 0.0008999);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 1), 11, 'Na', 'Sodium', 3, 22.98976928, 0.971);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 2), 12, 'Mg', 'Magnesium', 3, 24.305, 1.738);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 13), 13, 'Al', 'Aluminium', 3, 26.9815385, 2.698);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 14), 14, 'Si', 'Silicon', 3, 28.085, 2.3296);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 15), 15, 'P', 'Phosphorus', 3, 30.973761998, 1.82);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 16), 16, 'S', 'Sulfur', 3, 32.06, 2.067);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 17), 17, 'Cl', 'Chlorine', 3, 35.45, 0.003214);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 18), 18, 'Ar', 'Argon', 3, 39.948, 0.0017837);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 1), 19, 'K', 'Potassium', 4, 39.0983, 0.862);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 2), 20, 'Ca', 'Calcium', 4, 40.078, 1.54);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 3), 21, 'Sc', 'Scandium', 4, 44.955908, 2.989);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 4), 22, 'Ti', 'Titanium', 4, 47.867, 4.54);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 5), 23, 'V', 'Vanadium', 4, 50.9415, 6.11);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 6), 24, 'Cr', 'Chromium', 4, 51.9961, 7.15);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 7), 25, 'Mn', 'Manganese', 4, 54.938044, 7.44);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 8), 26, 'Fe', 'Iron', 4, 55.845, 7.874);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 9), 27, 'Co', 'Cobalt', 4, 58.933194, 8.86);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 10), 28, 'Ni', 'Nickel', 4, 58.6934, 8.912);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 11), 29, 'Cu', 'Copper', 4, 63.546, 8.96);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 12), 30, 'Zn', 'Zinc', 4, 65.38, 7.134);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 13), 31, 'Ga', 'Gallium', 4, 69.723, 5.907);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 14), 32, 'Ge', 'Germanium', 4, 72.63, 5.323);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 15), 33, 'As', 'Arsenic', 4, 74.921595, 5.776);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 16), 34, 'Se', 'Selenium', 4, 78.971, 4.809);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 17), 35, 'Br', 'Bromine', 4, 79.904, 3.122);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 18), 36, 'Kr', 'Krypton', 4, 83.798, 0.003733);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 1), 37, 'Rb', 'Rubidium', 5, 85.4678, 1.532);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 2), 38, 'Sr', 'Strontium', 5, 87.62, 2.64);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 3), 39, 'Y', 'Yttrium', 5, 88.90584, 4.469);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 4), 40, 'Zr', 'Zirconium', 5, 91.224, 6.506);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 5), 41, 'Nb', 'Niobium', 5, 92.90637, 8.57);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 6), 42, 'Mo', 'Molybdenum', 5, 95.95, 10.22);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 7), 43, 'Tc', 'Technetium', 5, 98, 11.5);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 8), 44, 'Ru', 'Ruthenium', 5, 101.07, 12.37);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 9), 45, 'Rh', 'Rhodium', 5, 102.9055, 12.41);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 10), 46, 'Pd', 'Palladium', 5, 106.42, 12.02);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 11), 47, 'Ag', 'Silver', 5, 107.8682, 10.501);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 12), 48, 'Cd', 'Cadmium', 5, 112.414, 8.69);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 13), 49, 'In', 'Indium', 5, 114.818, 7.31);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 14), 50, 'Sn', 'Tin', 5, 118.71, 7.287);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 15), 51, 'Sb', 'Antimony', 5, 121.76, 6.685);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 16), 52, 'Te', 'Tellurium', 5, 127.6, 6.232);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 17), 53, 'I', 'Iodine', 5, 126.90447, 4.93);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 18), 54, 'Xe', 'Xenon', 5, 131.293, 0.005887);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 1), 55, 'Cs', 'Caesium', 6, 132.90545196, 1.873);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 2), 56, 'Ba', 'Barium', 6, 137.327, 3.594);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 3), 57, 'La', 'Lanthanum', 6, 138.90547, 6.145);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES (NULL, 58, 'Ce', 'Cerium', 6, 140.116, 6.77);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES (NULL, 59, 'Pr', 'Praseodymium', 6, 140.90766, 6.773);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES (NULL, 60, 'Nd', 'Neodymium', 6, 144.242, 7.007);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES (NULL, 61, 'Pm', 'Promethium', 6, 145, 7.26);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES (NULL, 62, 'Sm', 'Samarium', 6, 150.36, 7.52);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES (NULL, 63, 'Eu', 'Europium', 6, 151.964, 5.243);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES (NULL, 64, 'Gd', 'Gadolinium', 6, 157.25, 7.895);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES (NULL, 65, 'Tb', 'Terbium', 6, 158.92535, 8.229);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES (NULL, 66, 'Dy', 'Dysprosium', 6, 162.5, 8.55);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES (NULL, 67, 'Ho', 'Holmium', 6, 164.93033, 8.795);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES (NULL, 68, 'Er', 'Erbium', 6, 167.259, 9.066);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES (NULL, 69, 'Tm', 'Thulium', 6, 168.93422, 9.321);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES (NULL, 70, 'Yb', 'Ytterbium', 6, 173.045, 6.965);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES (NULL, 71, 'Lu', 'Lutetium', 6, 174.9668, 9.84);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 4), 72, 'Hf', 'Hafnium', 6, 178.49, 13.31);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 5), 73, 'Ta', 'Tantalum', 6, 180.94788, 16.654);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 6), 74, 'W', 'Tungsten', 6, 183.84, 19.25);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 7), 75, 'Re', 'Rhenium', 6, 186.207, 21.02);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 8), 76, 'Os', 'Osmium', 6, 190.23, 22.61);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 9), 77, 'Ir', 'Iridium', 6, 192.217, 22.56);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 10), 78, 'Pt', 'Platinum', 6, 195.084, 21.46);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 11), 79, 'Au', 'Gold', 6, 196.966569, 19.282);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 12), 80, 'Hg', 'Mercury', 6, 200.592, 13.5336);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 13), 81, 'Tl', 'Thallium', 6, 204.38, 11.85);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 14), 82, 'Pb', 'Lead', 6, 207.2, 11.342);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 15), 83, 'Bi', 'Bismuth', 6, 208.9804, 9.807);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 16), 84, 'Po', 'Polonium', 6, 209, 9.32);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 17), 85, 'At', 'Astatine', 6, 210, 7);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 18), 86, 'Rn', 'Radon', 6, 222, 0.00973);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 1), 87, 'Fr', 'Francium', 7, 223, 1.87);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 2), 88, 'Ra', 'Radium', 7, 226, 5.5);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 3), 89, 'Ac', 'Actinium', 7, 227, 10.07);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = NULL), 90, 'Th', 'Thorium', 7, 232.0377, 11.72);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = NULL), 91, 'Pa', 'Protactinium', 7, 231.03588, 15.37);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = NULL), 92, 'U', 'Uranium', 7, 238.02891, 18.95);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = NULL), 93, 'Np', 'Neptunium', 7, 237, 20.45);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = NULL), 94, 'Pu', 'Plutonium', 7, 244, 19.84);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = NULL), 95, 'Am', 'Americium', 7, 243, 13.69);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = NULL), 96, 'Cm', 'Curium', 7, 247, 13.51);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = NULL), 97, 'Bk', 'Berkelium', 7, 247, 14.79);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = NULL), 98, 'Cf', 'Californium', 7, 251, 15.1);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = NULL), 99, 'Es', 'Einsteinium', 7, 252, 8.84);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = NULL), 100, 'Fm', 'Fermium', 7, 257, 9.7);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = NULL), 101, 'Md', 'Mendelevium', 7, 258, 10.3);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = NULL), 102, 'No', 'Nobelium', 7, 259, 9.9);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = NULL), 103, 'Lr', 'Lawrencium', 7, 266, 15.6);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 4), 104, 'Rf', 'Rutherfordium', 7, 267, 23.2);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 5), 105, 'Db', 'Dubnium', 7, 268, 29.3);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 6), 106, 'Sg', 'Seaborgium', 7, 269, 35);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 7), 107, 'Bh', 'Bohrium', 7, 270, 37.1);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 8), 108, 'Hs', 'Hassium', 7, 277, 40.7);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 9), 109, 'Mt', 'Meitnerium', 7, 278, 37.4);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 10), 110, 'Ds', 'Darmstadtium', 7, 281, 34.8);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 11), 111, 'Rg', 'Roentgenium', 7, 282, 28.7);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 12), 112, 'Cn', 'Copernicium', 7, 285, 23.7);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 13), 113, 'Nh', 'Nihonium', 7, 286, 16);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 14), 114, 'Fl', 'Flerovium', 7, 289, 14);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 15), 115, 'Mc', 'Moscovium', 7, 290, 13.5);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 16), 116, 'Lv', 'Livermorium', 7, 293, 12.9);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 17), 117, 'Ts', 'Tennessine', 7, 294, 7.2);
INSERT INTO dbo.Element (GroupID, AtomicNumber, Symbol, Name, Period, AtomicWeight, Density) VALUES ((SELECT ID FROM dbo.[Group] WHERE Number = 18), 118, 'Og', 'Oganesson', 7, 294, 5);

COMMIT